### PR TITLE
fix offsets not work

### PR DESCRIPTION
**Pull request by MaYecha**
In fact, I am a Chinese in your QQ group
I'm not very good at using pull requests
I directly forked your warehouse for modification
I don't know if pull requests are used this way, if not, just look at my fork repository
I only used the base address of the 4.6.3 source code to read it, and it was successful

事实上我是一个在你qq群的中国人
pull request我不太会用
我直接fork了你的仓库进行修改
我不知道pull request是不是这么用的，如果不是您就直接看我fork的仓库
我只是用了4.6.3的源码的基址读取，并且成功了

### CODE REVIEW

**Comment by CowNowB** [comment]
OK

**Comment by CowNowB** [comment]
Big Thanks

**Comment by MaYecha** [comment]
image
爱你宝贝，我不是倒卖的
：）

**Comment by CowNowB** [comment]
> image 爱你宝贝，我不是倒卖的 ：）

😋😋

**Pull request merged**
